spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/visits
    username: elhilali
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/